version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
    day: friday
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
    day: friday
  open-pull-requests-limit: 99
- package-ecosystem: bundler
  directory: "/contrib/cloudformation-template"
  schedule:
    interval: weekly
    day: friday
  open-pull-requests-limit: 99
