version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: monthly
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 99
- package-ecosystem: bundler
  directory: "/contrib/cloudformation-template"
  schedule:
    interval: monthly
  open-pull-requests-limit: 99

- package-ecosystem: docker
  directory: /contrib/scripts/bootstrap-via-installer
  schedule:
    interval: daily

- package-ecosystem: docker
  directory: /contrib/scripts/bootstrap-without-installed-agent
  schedule:
    interval: daily
