version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 99
  - package-ecosystem: bundler
    directory: /contrib/cloudformation-template
    schedule:
      interval: monthly
    open-pull-requests-limit: 99
    allow:
      - dependency-type: all
    groups:
      ruby-deps:
        patterns:
          - "*"
